-- PulseGear incremental migrations (combined)
-- Generated by prisma/sql/scripts/build-sql-bundle.mjs
-- Prefer 01_full_schema.sql for fresh databases.

-- >>> 0001_init
-- CreateEnum
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PAID', 'PAYMENT_FAILED', 'EXPIRED', 'FULFILLED', 'CANCELED', 'REFUNDED');
CREATE TYPE "InventoryMovementType" AS ENUM ('SALE', 'ADJUSTMENT', 'RESTOCK');

-- CreateTable
CREATE TABLE "Product" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "shortDescription" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "status" "ProductStatus" NOT NULL DEFAULT 'ACTIVE',
  "badge" TEXT,
  "rating" DECIMAL(2,1) NOT NULL DEFAULT 0,
  "reviewCount" INTEGER NOT NULL DEFAULT 0,
  "benefits" TEXT[],
  "features" TEXT[],
  "useCases" TEXT[],
  "bundleEligible" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductVariant" (
  "id" TEXT NOT NULL,
  "productId" TEXT NOT NULL,
  "sku" TEXT NOT NULL,
  "color" TEXT NOT NULL,
  "size" TEXT NOT NULL,
  "priceCents" INTEGER NOT NULL,
  "compareAtPriceCents" INTEGER,
  "stock" INTEGER NOT NULL DEFAULT 0,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductImage" (
  "id" TEXT NOT NULL,
  "productId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "alt" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "ProductImage_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Collection" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "description" TEXT,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "Collection_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductCollection" (
  "productId" TEXT NOT NULL,
  "collectionId" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "ProductCollection_pkey" PRIMARY KEY ("productId", "collectionId")
);

CREATE TABLE "Order" (
  "id" TEXT NOT NULL,
  "orderNo" TEXT NOT NULL,
  "email" TEXT,
  "status" "OrderStatus" NOT NULL DEFAULT 'PENDING',
  "currency" TEXT NOT NULL DEFAULT 'usd',
  "subtotalCents" INTEGER NOT NULL,
  "shippingCents" INTEGER NOT NULL,
  "discountCents" INTEGER NOT NULL DEFAULT 0,
  "totalCents" INTEGER NOT NULL,
  "stripeCheckoutSessionId" TEXT,
  "stripePaymentIntentId" TEXT,
  "paymentMethodType" TEXT,
  "customerCountry" TEXT,
  "shippingAddress" JSONB,
  "billingAddress" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "OrderItem" (
  "id" TEXT NOT NULL,
  "orderId" TEXT NOT NULL,
  "productId" TEXT NOT NULL,
  "variantId" TEXT NOT NULL,
  "titleSnapshot" TEXT NOT NULL,
  "skuSnapshot" TEXT NOT NULL,
  "colorSnapshot" TEXT NOT NULL,
  "sizeSnapshot" TEXT NOT NULL,
  "quantity" INTEGER NOT NULL,
  "unitPriceCents" INTEGER NOT NULL,
  "lineTotalCents" INTEGER NOT NULL,
  CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PaymentEvent" (
  "id" TEXT NOT NULL,
  "stripeEventId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "orderId" TEXT,
  "payload" JSONB NOT NULL,
  "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PaymentEvent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "InventoryMovement" (
  "id" TEXT NOT NULL,
  "variantId" TEXT NOT NULL,
  "orderId" TEXT,
  "type" "InventoryMovementType" NOT NULL,
  "quantity" INTEGER NOT NULL,
  "reason" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "InventoryMovement_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");
CREATE UNIQUE INDEX "ProductVariant_sku_key" ON "ProductVariant"("sku");
CREATE INDEX "ProductVariant_productId_idx" ON "ProductVariant"("productId");
CREATE INDEX "ProductVariant_color_size_idx" ON "ProductVariant"("color", "size");
CREATE INDEX "ProductImage_productId_idx" ON "ProductImage"("productId");
CREATE UNIQUE INDEX "Collection_slug_key" ON "Collection"("slug");
CREATE INDEX "ProductCollection_collectionId_idx" ON "ProductCollection"("collectionId");
CREATE UNIQUE INDEX "Order_orderNo_key" ON "Order"("orderNo");
CREATE UNIQUE INDEX "Order_stripeCheckoutSessionId_key" ON "Order"("stripeCheckoutSessionId");
CREATE INDEX "Order_status_idx" ON "Order"("status");
CREATE INDEX "Order_stripePaymentIntentId_idx" ON "Order"("stripePaymentIntentId");
CREATE INDEX "OrderItem_orderId_idx" ON "OrderItem"("orderId");
CREATE INDEX "OrderItem_variantId_idx" ON "OrderItem"("variantId");
CREATE UNIQUE INDEX "PaymentEvent_stripeEventId_key" ON "PaymentEvent"("stripeEventId");
CREATE INDEX "InventoryMovement_variantId_idx" ON "InventoryMovement"("variantId");
CREATE INDEX "InventoryMovement_orderId_idx" ON "InventoryMovement"("orderId");

ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductCollection" ADD CONSTRAINT "ProductCollection_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductCollection" ADD CONSTRAINT "ProductCollection_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentEvent" ADD CONSTRAINT "PaymentEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryMovement" ADD CONSTRAINT "InventoryMovement_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- >>> 0002_admin_inventory_fields
ALTER TABLE "ProductVariant"
ADD COLUMN "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN "weightGrams" INTEGER;

-- >>> 0003_product_seo_fields
ALTER TABLE "Product"
ADD COLUMN "seoTitle" TEXT,
ADD COLUMN "seoDescription" TEXT,
ADD COLUMN "canonicalUrl" TEXT,
ADD COLUMN "ogImageUrl" TEXT;

-- >>> 0004_admin_auth_tables
-- CreateEnum
CREATE TYPE "AdminRoleName" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'OPERATOR', 'CONTENT_EDITOR', 'ANALYST', 'VIEWER');

-- CreateTable
CREATE TABLE "AdminRole" (
  "id" TEXT NOT NULL,
  "name" "AdminRoleName" NOT NULL,
  "label" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AdminRole_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AdminUser" (
  "id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "lastLoginAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "roleId" TEXT NOT NULL,
  CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AuditLog" (
  "id" TEXT NOT NULL,
  "actorId" TEXT,
  "action" TEXT NOT NULL,
  "resource" TEXT NOT NULL,
  "resourceId" TEXT,
  "details" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AdminRole_name_key" ON "AdminRole"("name");
CREATE UNIQUE INDEX "AdminUser_email_key" ON "AdminUser"("email");
CREATE INDEX "AdminUser_roleId_idx" ON "AdminUser"("roleId");
CREATE INDEX "AuditLog_actorId_idx" ON "AuditLog"("actorId");
CREATE INDEX "AuditLog_resource_resourceId_idx" ON "AuditLog"("resource", "resourceId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- AddForeignKey
ALTER TABLE "AdminUser" ADD CONSTRAINT "AdminUser_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "AdminRole"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- >>> 0005_content_management_cms
CREATE TYPE "ContentType" AS ENUM ('GUIDE', 'FAQ', 'COLLECTION_PAGE');
CREATE TYPE "ContentStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

CREATE TABLE "ContentEntry" (
  "id" TEXT NOT NULL,
  "type" "ContentType" NOT NULL,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "status" "ContentStatus" NOT NULL DEFAULT 'DRAFT',
  "seoTitle" TEXT,
  "seoDescription" TEXT,
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ContentEntry_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "GuideContent" (
  "entryId" TEXT NOT NULL,
  "dek" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "authorName" TEXT NOT NULL,
  "authorRole" TEXT NOT NULL,
  "readTime" TEXT NOT NULL,
  "sections" JSONB NOT NULL,
  "faq" JSONB NOT NULL,
  "relatedProducts" JSONB NOT NULL,
  "relatedCollections" JSONB NOT NULL,
  "relatedGuides" JSONB NOT NULL,
  CONSTRAINT "GuideContent_pkey" PRIMARY KEY ("entryId")
);

CREATE TABLE "FaqContent" (
  "entryId" TEXT NOT NULL,
  "items" JSONB NOT NULL,
  CONSTRAINT "FaqContent_pkey" PRIMARY KEY ("entryId")
);

CREATE TABLE "CollectionLandingContent" (
  "entryId" TEXT NOT NULL,
  "pathname" TEXT NOT NULL,
  "scenario" TEXT,
  "intro" TEXT,
  "category" TEXT,
  "useCase" TEXT,
  "relatedGuideSlugs" JSONB NOT NULL,
  CONSTRAINT "CollectionLandingContent_pkey" PRIMARY KEY ("entryId")
);

CREATE UNIQUE INDEX "ContentEntry_type_slug_key" ON "ContentEntry"("type", "slug");
CREATE INDEX "ContentEntry_type_status_idx" ON "ContentEntry"("type", "status");
CREATE UNIQUE INDEX "CollectionLandingContent_pathname_key" ON "CollectionLandingContent"("pathname");

ALTER TABLE "GuideContent" ADD CONSTRAINT "GuideContent_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "ContentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FaqContent" ADD CONSTRAINT "FaqContent_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "ContentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CollectionLandingContent" ADD CONSTRAINT "CollectionLandingContent_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "ContentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- >>> 0006_admin_order_management
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED');
CREATE TYPE "FulfillmentStatus" AS ENUM ('UNFULFILLED', 'FULFILLED');

ALTER TABLE "Order"
ADD COLUMN "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
ADD COLUMN "fulfillmentStatus" "FulfillmentStatus" NOT NULL DEFAULT 'UNFULFILLED',
ADD COLUMN "fulfilledAt" TIMESTAMP(3);

UPDATE "Order"
SET "paymentStatus" = CASE
  WHEN "status" IN ('PAID', 'FULFILLED') THEN 'PAID'::"PaymentStatus"
  WHEN "status" IN ('PAYMENT_FAILED', 'EXPIRED', 'CANCELED') THEN 'FAILED'::"PaymentStatus"
  WHEN "status" = 'REFUNDED' THEN 'REFUNDED'::"PaymentStatus"
  ELSE 'PENDING'::"PaymentStatus"
END,
"fulfillmentStatus" = CASE
  WHEN "status" = 'FULFILLED' THEN 'FULFILLED'::"FulfillmentStatus"
  ELSE 'UNFULFILLED'::"FulfillmentStatus"
END,
"fulfilledAt" = CASE
  WHEN "status" = 'FULFILLED' THEN "updatedAt"
  ELSE NULL
END;

CREATE TABLE "OrderNote" (
  "id" TEXT NOT NULL,
  "orderId" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "createdByAdminId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OrderNote_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "OrderStatusEvent" (
  "id" TEXT NOT NULL,
  "orderId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "fromValue" TEXT,
  "toValue" TEXT,
  "details" JSONB,
  "createdByAdminId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OrderStatusEvent_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Order_paymentStatus_fulfillmentStatus_idx" ON "Order"("paymentStatus", "fulfillmentStatus");
CREATE INDEX "OrderNote_orderId_createdAt_idx" ON "OrderNote"("orderId", "createdAt");
CREATE INDEX "OrderNote_createdByAdminId_idx" ON "OrderNote"("createdByAdminId");
CREATE INDEX "OrderStatusEvent_orderId_createdAt_idx" ON "OrderStatusEvent"("orderId", "createdAt");
CREATE INDEX "OrderStatusEvent_createdByAdminId_idx" ON "OrderStatusEvent"("createdByAdminId");

ALTER TABLE "OrderNote" ADD CONSTRAINT "OrderNote_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderNote" ADD CONSTRAINT "OrderNote_createdByAdminId_fkey" FOREIGN KEY ("createdByAdminId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OrderStatusEvent" ADD CONSTRAINT "OrderStatusEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderStatusEvent" ADD CONSTRAINT "OrderStatusEvent_createdByAdminId_fkey" FOREIGN KEY ("createdByAdminId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- >>> 0007_admin_settings
CREATE TABLE "AdminSettings" (
  "id" TEXT NOT NULL,
  "storefrontUrl" TEXT NOT NULL,
  "supportEmail" TEXT NOT NULL,
  "checkoutCurrency" TEXT NOT NULL DEFAULT 'usd',
  "timezone" TEXT NOT NULL DEFAULT 'America/Los_Angeles',
  "shippingCountries" TEXT[] DEFAULT ARRAY['US','GB']::TEXT[],
  "defaultFulfillmentSlaDays" INTEGER NOT NULL DEFAULT 3,
  "returnsPolicyUrl" TEXT,
  "orderAutoFulfill" BOOLEAN NOT NULL DEFAULT false,
  "primaryPaymentProvider" TEXT NOT NULL DEFAULT 'Stripe Checkout',
  "stripeAutomaticPaymentMethods" BOOLEAN NOT NULL DEFAULT true,
  "paymentFailureMessage" TEXT,
  "adminSessionTtlHours" INTEGER NOT NULL DEFAULT 12,
  "auditLoggingEnabled" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AdminSettings_pkey" PRIMARY KEY ("id")
);

INSERT INTO "AdminSettings" (
  "id",
  "storefrontUrl",
  "supportEmail",
  "checkoutCurrency",
  "timezone",
  "shippingCountries",
  "defaultFulfillmentSlaDays",
  "returnsPolicyUrl",
  "orderAutoFulfill",
  "primaryPaymentProvider",
  "stripeAutomaticPaymentMethods",
  "paymentFailureMessage",
  "adminSessionTtlHours",
  "auditLoggingEnabled"
)
VALUES (
  'default',
  'http://localhost:3000',
  'support@pulsegear.local',
  'usd',
  'America/Los_Angeles',
  ARRAY['US','GB']::TEXT[],
  3,
  '/faq',
  false,
  'Stripe Checkout',
  true,
  'Retry checkout from cart if payment is not confirmed.',
  12,
  true
)
ON CONFLICT ("id") DO NOTHING;

-- >>> 0008_seo_automation
CREATE TYPE "SeoPageType" AS ENUM ('HOME', 'PRODUCT', 'COLLECTION', 'GUIDE', 'FAQ', 'LANDING');
CREATE TYPE "SeoIssueStatus" AS ENUM ('OPEN', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'RESOLVED');
CREATE TYPE "SeoRecommendationStatus" AS ENUM ('DRAFT', 'REVIEWED', 'APPLIED', 'REJECTED');
CREATE TYPE "ContentOpportunityStatus" AS ENUM ('NEW', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'DONE');
CREATE TYPE "ContentPipelineStatus" AS ENUM ('OPPORTUNITY', 'BRIEF_GENERATED', 'DRAFT_GENERATED', 'NEEDS_REVIEW', 'APPROVED', 'PUBLISHED', 'MONITORING');
CREATE TYPE "InternalLinkSuggestionStatus" AS ENUM ('NEW', 'ACCEPTED', 'REJECTED', 'APPLIED');

CREATE TABLE "SeoPage" (
  "id" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "pageType" "SeoPageType" NOT NULL,
  "title" TEXT,
  "metaDescription" TEXT,
  "canonicalUrl" TEXT,
  "h1Count" INTEGER NOT NULL DEFAULT 0,
  "missingAltCount" INTEGER NOT NULL DEFAULT 0,
  "inSitemap" BOOLEAN NOT NULL DEFAULT false,
  "isIndexable" BOOLEAN NOT NULL DEFAULT true,
  "hasProductJsonLd" BOOLEAN NOT NULL DEFAULT false,
  "hasBreadcrumbJsonLd" BOOLEAN NOT NULL DEFAULT false,
  "healthScore" INTEGER NOT NULL DEFAULT 100,
  "lastCheckedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SeoPage_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SeoIssue" (
  "id" TEXT NOT NULL,
  "seoPageId" TEXT NOT NULL,
  "issueType" TEXT NOT NULL,
  "severity" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "status" "SeoIssueStatus" NOT NULL DEFAULT 'OPEN',
  "metadata" JSONB,
  "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolvedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SeoIssue_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SeoRecommendation" (
  "id" TEXT NOT NULL,
  "seoPageId" TEXT,
  "recommendationType" TEXT NOT NULL,
  "resourceType" TEXT NOT NULL,
  "resourceId" TEXT,
  "draftPayload" JSONB NOT NULL,
  "reason" TEXT NOT NULL,
  "priority" TEXT NOT NULL,
  "status" "SeoRecommendationStatus" NOT NULL DEFAULT 'DRAFT',
  "isAiDraft" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "appliedAt" TIMESTAMP(3),
  CONSTRAINT "SeoRecommendation_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SearchConsoleQueryDaily" (
  "id" TEXT NOT NULL,
  "siteUrl" TEXT NOT NULL,
  "page" TEXT NOT NULL,
  "query" TEXT NOT NULL,
  "country" TEXT NOT NULL,
  "device" TEXT NOT NULL,
  "date" TIMESTAMP(3) NOT NULL,
  "clicks" INTEGER NOT NULL,
  "impressions" INTEGER NOT NULL,
  "ctr" DECIMAL(5,4) NOT NULL,
  "position" DECIMAL(6,2) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SearchConsoleQueryDaily_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SearchConsolePageDaily" (
  "id" TEXT NOT NULL,
  "siteUrl" TEXT NOT NULL,
  "page" TEXT NOT NULL,
  "country" TEXT NOT NULL,
  "device" TEXT NOT NULL,
  "date" TIMESTAMP(3) NOT NULL,
  "clicks" INTEGER NOT NULL,
  "impressions" INTEGER NOT NULL,
  "ctr" DECIMAL(5,4) NOT NULL,
  "position" DECIMAL(6,2) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SearchConsolePageDaily_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Ga4LandingPageDaily" (
  "id" TEXT NOT NULL,
  "landingPage" TEXT NOT NULL,
  "sourceMedium" TEXT NOT NULL,
  "date" TIMESTAMP(3) NOT NULL,
  "sessions" INTEGER NOT NULL,
  "totalUsers" INTEGER NOT NULL,
  "pageViews" INTEGER NOT NULL,
  "viewItem" INTEGER NOT NULL,
  "addToCart" INTEGER NOT NULL,
  "beginCheckout" INTEGER NOT NULL,
  "purchase" INTEGER NOT NULL,
  "revenue" DECIMAL(12,2) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Ga4LandingPageDaily_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ContentOpportunity" (
  "id" TEXT NOT NULL,
  "opportunityType" TEXT NOT NULL,
  "keyword" TEXT,
  "currentPage" TEXT,
  "suggestedAction" TEXT NOT NULL,
  "priority" TEXT NOT NULL,
  "expectedImpact" TEXT NOT NULL,
  "status" "ContentOpportunityStatus" NOT NULL DEFAULT 'NEW',
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentOpportunity_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ContentBrief" (
  "id" TEXT NOT NULL,
  "sourceOpportunityId" TEXT,
  "title" TEXT NOT NULL,
  "targetKeyword" TEXT NOT NULL,
  "outline" JSONB,
  "draftContent" TEXT,
  "relatedProductIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "relatedCollectionSlugs" TEXT[] DEFAULT ARRAY[]::TEXT[],
  "status" "ContentPipelineStatus" NOT NULL DEFAULT 'OPPORTUNITY',
  "publishedContentEntryId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentBrief_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "InternalLinkSuggestion" (
  "id" TEXT NOT NULL,
  "sourcePage" TEXT NOT NULL,
  "targetPage" TEXT NOT NULL,
  "anchorText" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "priority" TEXT NOT NULL,
  "status" "InternalLinkSuggestionStatus" NOT NULL DEFAULT 'NEW',
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "InternalLinkSuggestion_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SeoChangeLog" (
  "id" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "resourceType" TEXT NOT NULL,
  "resourceId" TEXT,
  "oldValue" JSONB,
  "newValue" JSONB,
  "operatorId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SeoChangeLog_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "SeoPage_url_key" ON "SeoPage"("url");
CREATE INDEX "SeoPage_pageType_idx" ON "SeoPage"("pageType");
CREATE INDEX "SeoPage_healthScore_idx" ON "SeoPage"("healthScore");
CREATE INDEX "SeoIssue_seoPageId_status_idx" ON "SeoIssue"("seoPageId", "status");
CREATE INDEX "SeoIssue_issueType_severity_idx" ON "SeoIssue"("issueType", "severity");
CREATE INDEX "SeoRecommendation_status_priority_idx" ON "SeoRecommendation"("status", "priority");
CREATE INDEX "SeoRecommendation_resourceType_resourceId_idx" ON "SeoRecommendation"("resourceType", "resourceId");
CREATE UNIQUE INDEX "SearchConsoleQueryDaily_siteUrl_date_query_page_country_device_key" ON "SearchConsoleQueryDaily"("siteUrl", "date", "query", "page", "country", "device");
CREATE UNIQUE INDEX "SearchConsolePageDaily_siteUrl_date_page_country_device_key" ON "SearchConsolePageDaily"("siteUrl", "date", "page", "country", "device");
CREATE UNIQUE INDEX "Ga4LandingPageDaily_landingPage_sourceMedium_date_key" ON "Ga4LandingPageDaily"("landingPage", "sourceMedium", "date");
CREATE INDEX "ContentOpportunity_status_priority_idx" ON "ContentOpportunity"("status", "priority");
CREATE INDEX "ContentOpportunity_opportunityType_idx" ON "ContentOpportunity"("opportunityType");
CREATE INDEX "ContentBrief_status_idx" ON "ContentBrief"("status");
CREATE INDEX "InternalLinkSuggestion_status_priority_idx" ON "InternalLinkSuggestion"("status", "priority");
CREATE INDEX "SeoChangeLog_resourceType_resourceId_idx" ON "SeoChangeLog"("resourceType", "resourceId");
CREATE INDEX "SeoChangeLog_operatorId_createdAt_idx" ON "SeoChangeLog"("operatorId", "createdAt");

ALTER TABLE "SeoIssue" ADD CONSTRAINT "SeoIssue_seoPageId_fkey" FOREIGN KEY ("seoPageId") REFERENCES "SeoPage"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SeoRecommendation" ADD CONSTRAINT "SeoRecommendation_seoPageId_fkey" FOREIGN KEY ("seoPageId") REFERENCES "SeoPage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ContentBrief" ADD CONSTRAINT "ContentBrief_sourceOpportunityId_fkey" FOREIGN KEY ("sourceOpportunityId") REFERENCES "ContentOpportunity"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SeoChangeLog" ADD CONSTRAINT "SeoChangeLog_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- >>> 0009_copy_config
CREATE TABLE "SiteSetting" (
  "key" TEXT NOT NULL,
  "value" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("key")
);

CREATE TABLE "UiCopy" (
  "key" TEXT NOT NULL,
  "locale" TEXT NOT NULL DEFAULT 'en-US',
  "value" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UiCopy_pkey" PRIMARY KEY ("key","locale")
);

CREATE TABLE "ContentTemplate" (
  "key" TEXT NOT NULL,
  "locale" TEXT NOT NULL DEFAULT 'en-US',
  "name" TEXT NOT NULL,
  "content" JSONB NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'ACTIVE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ContentTemplate_pkey" PRIMARY KEY ("key","locale")
);

CREATE TABLE "SeoAutomationRule" (
  "key" TEXT NOT NULL,
  "value" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SeoAutomationRule_pkey" PRIMARY KEY ("key")
);

-- >>> 0010_product_research
CREATE TYPE "ProductCandidateSource" AS ENUM ('MANUAL', 'AI_GENERATED', 'CSV', 'ALIBABA_LINK', 'SUPPLIER_QUOTE');
CREATE TYPE "ProductCandidateStatus" AS ENUM ('NEW', 'RESEARCHING', 'WATCH', 'SAMPLE', 'TEST', 'APPROVED', 'REJECTED', 'HIGH_RISK_REVIEW');
CREATE TYPE "ProductResearchRecommendedAction" AS ENUM ('SAMPLE', 'TEST', 'WATCH', 'REJECT', 'REVIEW');
CREATE TYPE "SupplierPlatform" AS ENUM ('ALIBABA', 'ALIEXPRESS', 'CJ_DROPSHIPPING', 'AGENT', 'OTHER');
CREATE TYPE "ProductResearchSignalSource" AS ENUM ('GOOGLE_TRENDS', 'GSC', 'GA4', 'AMAZON', 'ETSY', 'TIKTOK', 'ALIBABA', 'MANUAL');
CREATE TYPE "ProductTestLaunchStatus" AS ENUM ('PLANNED', 'RUNNING', 'COMPLETED', 'STOPPED');
CREATE TYPE "ProductResearchDecisionType" AS ENUM ('SAMPLE', 'TEST', 'WATCH', 'APPROVE', 'REJECT', 'CONVERT_TO_PRODUCT');
CREATE TYPE "ProductResearchImportSource" AS ENUM ('AI', 'CSV', 'ALIBABA_LINK', 'SUPPLIER_QUOTE', 'MANUAL');
CREATE TYPE "ProductResearchRiskSeverity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'BLOCKING');

CREATE TABLE "ProductCandidate" (
  "id" TEXT NOT NULL,
  "productName" TEXT NOT NULL,
  "chineseName" TEXT,
  "slugSuggestion" TEXT,
  "category" TEXT NOT NULL,
  "targetMarket" TEXT NOT NULL,
  "targetAudience" TEXT,
  "useCase" TEXT,
  "description" TEXT,
  "notes" TEXT,
  "brandAngle" TEXT,
  "positioningSummary" TEXT,
  "alibabaKeywords" TEXT,
  "source" "ProductCandidateSource" NOT NULL,
  "sourceUrl" TEXT,
  "rawImportData" JSONB,
  "aiDraftPayload" JSONB,
  "status" "ProductCandidateStatus" NOT NULL DEFAULT 'NEW',
  "recommendedAction" "ProductResearchRecommendedAction" NOT NULL DEFAULT 'WATCH',
  "finalScore" DOUBLE PRECISION,
  "riskScore" INTEGER,
  "validatedScore" DOUBLE PRECISION,
  "possibleDuplicateOfId" TEXT,
  "createdById" TEXT,
  "approvedById" TEXT,
  "approvedAt" TIMESTAMP(3),
  "convertedProductId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductCandidate_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductCandidateScore" (
  "id" TEXT NOT NULL,
  "candidateId" TEXT NOT NULL,
  "marketDemandScore" INTEGER NOT NULL,
  "trendSeasonalityScore" INTEGER NOT NULL,
  "competitionGapScore" INTEGER NOT NULL,
  "marginPotentialScore" INTEGER NOT NULL,
  "logisticsFitScore" INTEGER NOT NULL,
  "brandabilityScore" INTEGER NOT NULL,
  "supplierQualityScore" INTEGER NOT NULL,
  "riskScore" INTEGER NOT NULL,
  "riskInverseScore" INTEGER NOT NULL,
  "testabilityScore" INTEGER NOT NULL,
  "finalScore" DOUBLE PRECISION NOT NULL,
  "scoringVersion" TEXT NOT NULL,
  "scoreReasonJson" JSONB,
  "isManualAdjusted" BOOLEAN NOT NULL DEFAULT false,
  "manualAdjustmentReason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "computedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductCandidateScore_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Supplier" (
  "id" TEXT NOT NULL,
  "platform" "SupplierPlatform" NOT NULL,
  "name" TEXT NOT NULL,
  "url" TEXT,
  "country" TEXT,
  "verifiedSupplier" BOOLEAN NOT NULL DEFAULT false,
  "tradeAssurance" BOOLEAN NOT NULL DEFAULT false,
  "yearsOnPlatform" INTEGER,
  "responseRate" DOUBLE PRECISION,
  "moq" INTEGER,
  "samplePriceCents" INTEGER,
  "unitPriceCents" INTEGER,
  "customLogoMoq" INTEGER,
  "customPackagingMoq" INTEGER,
  "leadTimeDays" INTEGER,
  "shippingToUSCents" INTEGER,
  "shippingToUKCents" INTEGER,
  "certifications" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductCandidateSupplier" (
  "candidateId" TEXT NOT NULL,
  "supplierId" TEXT NOT NULL,
  "quotedUnitPriceCents" INTEGER,
  "quotedMoq" INTEGER,
  "quotedLeadTimeDays" INTEGER,
  "quoteFileUrl" TEXT,
  "notes" TEXT,
  CONSTRAINT "ProductCandidateSupplier_pkey" PRIMARY KEY ("candidateId", "supplierId")
);

CREATE TABLE "ProductResearchSignal" (
  "id" TEXT NOT NULL,
  "candidateId" TEXT NOT NULL,
  "source" "ProductResearchSignalSource" NOT NULL,
  "metricName" TEXT NOT NULL,
  "metricValue" DOUBLE PRECISION NOT NULL,
  "rawData" JSONB,
  "collectedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ProductResearchSignal_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductTestLaunch" (
  "id" TEXT NOT NULL,
  "candidateId" TEXT NOT NULL,
  "landingPageUrl" TEXT,
  "channel" TEXT NOT NULL,
  "channelDetail" TEXT,
  "adSpendCents" INTEGER NOT NULL DEFAULT 0,
  "impressions" INTEGER NOT NULL DEFAULT 0,
  "clicks" INTEGER NOT NULL DEFAULT 0,
  "ctr" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "productViews" INTEGER NOT NULL DEFAULT 0,
  "addToCart" INTEGER NOT NULL DEFAULT 0,
  "addToCartRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "beginCheckout" INTEGER NOT NULL DEFAULT 0,
  "checkoutRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "purchases" INTEGER NOT NULL DEFAULT 0,
  "purchaseRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "revenueCents" INTEGER NOT NULL DEFAULT 0,
  "refunds" INTEGER NOT NULL DEFAULT 0,
  "customerFeedbackScore" INTEGER,
  "refundRiskScore" INTEGER,
  "customerFeedbackSummary" TEXT,
  "notes" TEXT,
  "testScore" DOUBLE PRECISION,
  "status" "ProductTestLaunchStatus" NOT NULL DEFAULT 'PLANNED',
  "startedAt" TIMESTAMP(3),
  "endedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductTestLaunch_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductResearchDecision" (
  "id" TEXT NOT NULL,
  "candidateId" TEXT NOT NULL,
  "decision" "ProductResearchDecisionType" NOT NULL,
  "reason" TEXT,
  "operatorId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductResearchDecision_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductResearchImportBatch" (
  "id" TEXT NOT NULL,
  "source" "ProductResearchImportSource" NOT NULL,
  "fileName" TEXT,
  "totalRows" INTEGER NOT NULL DEFAULT 0,
  "createdCount" INTEGER NOT NULL DEFAULT 0,
  "skippedCount" INTEGER NOT NULL DEFAULT 0,
  "duplicateCount" INTEGER NOT NULL DEFAULT 0,
  "invalidCount" INTEGER NOT NULL DEFAULT 0,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductResearchImportBatch_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductResearchRiskFlag" (
  "id" TEXT NOT NULL,
  "candidateId" TEXT NOT NULL,
  "riskType" TEXT NOT NULL,
  "severity" "ProductResearchRiskSeverity" NOT NULL,
  "message" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductResearchRiskFlag_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ScoringRule" (
  "id" TEXT NOT NULL,
  "version" TEXT NOT NULL,
  "weights" JSONB NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT false,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ScoringRule_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "ScoringRule_version_key" ON "ScoringRule"("version");
CREATE INDEX "ProductCandidate_status_updatedAt_idx" ON "ProductCandidate"("status", "updatedAt");
CREATE INDEX "ProductCandidate_source_createdAt_idx" ON "ProductCandidate"("source", "createdAt");
CREATE INDEX "ProductCandidate_targetMarket_category_idx" ON "ProductCandidate"("targetMarket", "category");
CREATE INDEX "ProductCandidate_productName_idx" ON "ProductCandidate"("productName");
CREATE INDEX "ProductCandidate_productName_category_targetMarket_idx" ON "ProductCandidate"("productName", "category", "targetMarket");
CREATE INDEX "ProductCandidate_recommendedAction_idx" ON "ProductCandidate"("recommendedAction");
CREATE INDEX "ProductCandidate_finalScore_idx" ON "ProductCandidate"("finalScore");
CREATE INDEX "ProductCandidate_riskScore_idx" ON "ProductCandidate"("riskScore");
CREATE INDEX "ProductCandidate_possibleDuplicateOfId_idx" ON "ProductCandidate"("possibleDuplicateOfId");
CREATE INDEX "ProductCandidate_createdById_idx" ON "ProductCandidate"("createdById");
CREATE INDEX "ProductCandidate_approvedById_idx" ON "ProductCandidate"("approvedById");
CREATE INDEX "ProductCandidateScore_candidateId_createdAt_idx" ON "ProductCandidateScore"("candidateId", "createdAt");
CREATE INDEX "ProductCandidateScore_scoringVersion_idx" ON "ProductCandidateScore"("scoringVersion");
CREATE INDEX "Supplier_platform_country_idx" ON "Supplier"("platform", "country");
CREATE INDEX "Supplier_verifiedSupplier_tradeAssurance_idx" ON "Supplier"("verifiedSupplier", "tradeAssurance");
CREATE INDEX "Supplier_name_idx" ON "Supplier"("name");
CREATE INDEX "Supplier_url_idx" ON "Supplier"("url");
CREATE INDEX "ProductCandidateSupplier_supplierId_idx" ON "ProductCandidateSupplier"("supplierId");
CREATE INDEX "ProductResearchSignal_candidateId_source_idx" ON "ProductResearchSignal"("candidateId", "source");
CREATE INDEX "ProductResearchSignal_metricName_collectedAt_idx" ON "ProductResearchSignal"("metricName", "collectedAt");
CREATE INDEX "ProductTestLaunch_candidateId_status_idx" ON "ProductTestLaunch"("candidateId", "status");
CREATE INDEX "ProductTestLaunch_status_startedAt_idx" ON "ProductTestLaunch"("status", "startedAt");
CREATE INDEX "ProductResearchDecision_candidateId_createdAt_idx" ON "ProductResearchDecision"("candidateId", "createdAt");
CREATE INDEX "ProductResearchDecision_operatorId_createdAt_idx" ON "ProductResearchDecision"("operatorId", "createdAt");
CREATE INDEX "ProductResearchDecision_decision_createdAt_idx" ON "ProductResearchDecision"("decision", "createdAt");
CREATE INDEX "ProductResearchImportBatch_source_createdAt_idx" ON "ProductResearchImportBatch"("source", "createdAt");
CREATE INDEX "ProductResearchImportBatch_createdById_createdAt_idx" ON "ProductResearchImportBatch"("createdById", "createdAt");
CREATE INDEX "ProductResearchRiskFlag_candidateId_severity_idx" ON "ProductResearchRiskFlag"("candidateId", "severity");
CREATE INDEX "ProductResearchRiskFlag_severity_createdAt_idx" ON "ProductResearchRiskFlag"("severity", "createdAt");
CREATE INDEX "ScoringRule_isActive_createdAt_idx" ON "ScoringRule"("isActive", "createdAt");
CREATE INDEX "ScoringRule_createdById_idx" ON "ScoringRule"("createdById");

ALTER TABLE "ProductCandidate"
  ADD CONSTRAINT "ProductCandidate_possibleDuplicateOfId_fkey"
  FOREIGN KEY ("possibleDuplicateOfId") REFERENCES "ProductCandidate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductCandidate"
  ADD CONSTRAINT "ProductCandidate_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductCandidate"
  ADD CONSTRAINT "ProductCandidate_approvedById_fkey"
  FOREIGN KEY ("approvedById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductCandidate"
  ADD CONSTRAINT "ProductCandidate_convertedProductId_fkey"
  FOREIGN KEY ("convertedProductId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductCandidateScore"
  ADD CONSTRAINT "ProductCandidateScore_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductCandidateSupplier"
  ADD CONSTRAINT "ProductCandidateSupplier_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductCandidateSupplier"
  ADD CONSTRAINT "ProductCandidateSupplier_supplierId_fkey"
  FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductResearchSignal"
  ADD CONSTRAINT "ProductResearchSignal_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductTestLaunch"
  ADD CONSTRAINT "ProductTestLaunch_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductResearchDecision"
  ADD CONSTRAINT "ProductResearchDecision_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ProductResearchDecision"
  ADD CONSTRAINT "ProductResearchDecision_operatorId_fkey"
  FOREIGN KEY ("operatorId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductResearchImportBatch"
  ADD CONSTRAINT "ProductResearchImportBatch_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "ProductResearchRiskFlag"
  ADD CONSTRAINT "ProductResearchRiskFlag_candidateId_fkey"
  FOREIGN KEY ("candidateId") REFERENCES "ProductCandidate"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ScoringRule"
  ADD CONSTRAINT "ScoringRule_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- >>> 0011_product_bilingual_fields
ALTER TABLE "Product"
ADD COLUMN "titleEn" TEXT,
ADD COLUMN "titleZh" TEXT,
ADD COLUMN "shortDescriptionEn" TEXT,
ADD COLUMN "shortDescriptionZh" TEXT,
ADD COLUMN "descriptionEn" TEXT,
ADD COLUMN "descriptionZh" TEXT,
ADD COLUMN "seoTitleEn" TEXT,
ADD COLUMN "seoTitleZh" TEXT,
ADD COLUMN "seoDescriptionEn" TEXT,
ADD COLUMN "seoDescriptionZh" TEXT,
ADD COLUMN "benefitsEn" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
ADD COLUMN "benefitsZh" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
ADD COLUMN "featuresEn" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL,
ADD COLUMN "featuresZh" TEXT[] DEFAULT ARRAY[]::TEXT[] NOT NULL;

UPDATE "Product"
SET
  "titleEn" = "title",
  "shortDescriptionEn" = "shortDescription",
  "descriptionEn" = "description",
  "seoTitleEn" = "seoTitle",
  "seoDescriptionEn" = "seoDescription",
  "benefitsEn" = "benefits",
  "featuresEn" = "features"
WHERE
  "titleEn" IS NULL
  OR "shortDescriptionEn" IS NULL
  OR "descriptionEn" IS NULL;

-- >>> 0012_content_bilingual_fields
ALTER TABLE "ContentEntry"
  ADD COLUMN "titleEn" TEXT,
  ADD COLUMN "titleZh" TEXT,
  ADD COLUMN "seoTitleEn" TEXT,
  ADD COLUMN "seoTitleZh" TEXT,
  ADD COLUMN "seoDescriptionEn" TEXT,
  ADD COLUMN "seoDescriptionZh" TEXT;

ALTER TABLE "GuideContent"
  ADD COLUMN "dekEn" TEXT,
  ADD COLUMN "dekZh" TEXT,
  ADD COLUMN "categoryEn" TEXT,
  ADD COLUMN "categoryZh" TEXT,
  ADD COLUMN "authorRoleEn" TEXT,
  ADD COLUMN "authorRoleZh" TEXT,
  ADD COLUMN "readTimeEn" TEXT,
  ADD COLUMN "readTimeZh" TEXT,
  ADD COLUMN "sectionsEn" JSONB,
  ADD COLUMN "sectionsZh" JSONB,
  ADD COLUMN "faqEn" JSONB,
  ADD COLUMN "faqZh" JSONB;

ALTER TABLE "FaqContent"
  ADD COLUMN "itemsEn" JSONB,
  ADD COLUMN "itemsZh" JSONB;

UPDATE "ContentEntry"
SET
  "titleEn" = "title",
  "seoTitleEn" = "seoTitle",
  "seoDescriptionEn" = "seoDescription";

UPDATE "GuideContent"
SET
  "dekEn" = "dek",
  "categoryEn" = "category",
  "authorRoleEn" = "authorRole",
  "readTimeEn" = "readTime",
  "sectionsEn" = "sections",
  "faqEn" = "faq";

UPDATE "FaqContent"
SET
  "itemsEn" = "items";

-- >>> 0013_collection_landing_bilingual_intro
ALTER TABLE "CollectionLandingContent"
  ADD COLUMN "introEn" TEXT,
  ADD COLUMN "introZh" TEXT;

UPDATE "CollectionLandingContent"
SET "introEn" = "intro";

-- >>> 0014_static_page_content
ALTER TYPE "ContentType" ADD VALUE 'STATIC_PAGE';

CREATE TABLE "StaticPageContent" (
  "entryId" TEXT NOT NULL,
  "pageKey" TEXT NOT NULL,
  "pathname" TEXT NOT NULL,
  "content" JSONB NOT NULL,
  "contentEn" JSONB,
  "contentZh" JSONB,
  CONSTRAINT "StaticPageContent_pkey" PRIMARY KEY ("entryId"),
  CONSTRAINT "StaticPageContent_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "ContentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "StaticPageContent_pageKey_key" ON "StaticPageContent"("pageKey");
CREATE UNIQUE INDEX "StaticPageContent_pathname_key" ON "StaticPageContent"("pathname");

-- >>> 0015_product_research_risk_resolution
-- Add APPROVE to recommended action enum
ALTER TYPE "ProductResearchRecommendedAction" ADD VALUE IF NOT EXISTS 'APPROVE';

-- Risk flag resolution tracking
ALTER TABLE "ProductResearchRiskFlag"
ADD COLUMN IF NOT EXISTS "resolvedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "resolvedById" TEXT,
ADD COLUMN IF NOT EXISTS "resolutionNote" TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'ProductResearchRiskFlag_resolvedById_fkey'
  ) THEN
    ALTER TABLE "ProductResearchRiskFlag"
    ADD CONSTRAINT "ProductResearchRiskFlag_resolvedById_fkey"
    FOREIGN KEY ("resolvedById") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "ProductResearchRiskFlag_candidateId_resolvedAt_idx"
ON "ProductResearchRiskFlag"("candidateId", "resolvedAt");

-- >>> 0016_inventory_reservation
-- CreateEnum
CREATE TYPE "OrderInventoryStatus" AS ENUM ('OK', 'SHORT');

-- AlterEnum
ALTER TYPE "InventoryMovementType" ADD VALUE 'RESERVATION';
ALTER TYPE "InventoryMovementType" ADD VALUE 'RELEASE';

-- AlterTable
ALTER TABLE "ProductVariant" ADD COLUMN "reservedStock" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "inventoryStatus" "OrderInventoryStatus" NOT NULL DEFAULT 'OK';

-- CreateIndex
CREATE UNIQUE INDEX "InventoryMovement_orderId_variantId_type_key" ON "InventoryMovement"("orderId", "variantId", "type");

-- >>> 20260525011718_product_research
-- AlterTable
ALTER TABLE "AdminSettings" ALTER COLUMN "shippingCountries" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ContentBrief" ALTER COLUMN "relatedProductIds" DROP DEFAULT,
ALTER COLUMN "relatedCollectionSlugs" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ContentOpportunity" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ContentTemplate" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Ga4LandingPageDaily" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "InternalLinkSuggestion" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ProductCandidate" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ProductTestLaunch" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SearchConsolePageDaily" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SearchConsoleQueryDaily" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SeoAutomationRule" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SeoIssue" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SeoPage" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SeoRecommendation" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SiteSetting" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "UiCopy" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- CreateIndex
CREATE INDEX "Ga4LandingPageDaily_landingPage_date_idx" ON "Ga4LandingPageDaily"("landingPage", "date");

-- CreateIndex
CREATE INDEX "SearchConsolePageDaily_page_date_idx" ON "SearchConsolePageDaily"("page", "date");

-- CreateIndex
CREATE INDEX "SearchConsoleQueryDaily_page_date_idx" ON "SearchConsoleQueryDaily"("page", "date");

-- RenameIndex
ALTER INDEX "SearchConsoleQueryDaily_siteUrl_date_query_page_country_device_" RENAME TO "SearchConsoleQueryDaily_siteUrl_date_query_page_country_dev_key";

